### ISSUE TITLE
a VS template for vite+svelte

### ISSUE THREAD

**Issue by robertovanoli** [nelsontkq/dotnet-svelte-template#3]
hi @nelsontkq this is the only template I've found for VS and aspnet 6 so far and it's working great, so Thankyou for publishing.

I installed your template with `dotnet new --install Nelsontkq.Svelte ` then created a .net core app `dotnet new svelte`.

This installed a **_svelte-kit app_**  (not a **_svelte app_** as the name might suggest). The svelte.config.js has configs that are specific to svelte-kit. 
![image](https://user-images.githubusercontent.com/17762203/214557051-79f6dd25-d190-4d8d-80e8-edf8d230e3da.png)

Following your template, i'm trying to create an asp.net 6.0 project integrated with a **_svelte app_** (actually a vite+svelte app) 
- `dotnet new svelte`
- `rd ClientApp`
- `npm init vite`
- ![image](https://user-images.githubusercontent.com/17762203/214546659-494cf09f-d54d-4bc1-b7b7-8c7742cf9a88.png)

then I've tried to modify the svelte.config.js for my vite+svelte app in this way:
![image](https://user-images.githubusercontent.com/17762203/214552754-8e1c8be9-a015-4070-89de-afcb521cf356.png)

using `npm run dev` the server starts correctly, but the proxy configurations are not set. 

I'm quite new to svelte, Please can you suggest the exact config names to be used in svelte.config.js for my scenario?
or maybe it's possible to deploy TWO templates, one for the sveltekit+svelte scenario and one for the vite+svelte scenario?

thankyou very much RV

**Comment by nelsontkq** [comment]
I would guess that the issue that's occurring there is the port not being setup correctly. In this template the `.csproj` sets the spa proxy to https://localhost:44447. You can change it in the csproj or in the svelte config
